### ISSUE TITLE
Linux and Windows key bindings

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/Dependents#106]
The logic behind the `Cmd + Option + Up` is that it's like the key bindings for Goto Definition `Cmd + Option + Down`. Something equivalent for Linux and Windows would be helpful.

**Comment by dkebler** [comment]
I've got this covered including update to the readme.  Just waiting on solution to the widows long path bug so I can get Dependents installed and test bindings there.

Since they will be the same in both wondering if sublime first looks for the generic default version first and then if it finds for specific os like (OSX) then will load that.  That would be cleanest instead of one for each.  Too you might like my key and mouse binding choices better for osx as well and then all would be the same across all os.  

I see you added menu under preferences/package for package settings it would be nice add the bindings there too so it's easier to customize these.   See the sidebar enhancements package for example.  Hmmm...I should be able to figure this out so I'll add it to this enhancement.

**Comment by mrjoelkemp** [comment]
@dkebler I'm working on windows stuff and decided to just add the key bindings while I'm here. Trying to give you credit on the commit, but I don't know the email that you used to register with github. A username isn't enough (Need a name and email) so the author isn't exactly you. Mind sharing that email?

**Comment by mrjoelkemp** [comment]
Nevermind, found your info!
