### ISSUE TITLE
Error when trying to jump to dependency

### ISSUE THREAD

**Issue by mikesherov** [mrjoelkemp/Dependents#212]
```
project_settings: starting search for .deprc in:  /Users/sherov/code/***
project_settings: Closest folder with a deprc: /Users/sherov/code/***
project_settings: Using found .deprc within:  /Users/sherov/code/***/.deprc
node_dependents_editor_backend: node_path from settings:  
node_dependents_editor_backend: bin path /Users/sherov/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents-editor-backend/bin/cli.js
node_bridge: Node path: :/usr/local/bin
node_bridge: Executing:  node /Users/sherov/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents-editor-backend/bin/cli.js --filename=/Users/sherov/code/*** --get-config
command_setup: parsed config from backend {'nodePath': '', 'webpackConfig': '', 'buildConfig': '/Users/sherov/code/***/build.json', 'directory': '/Users/sherov/code/***', 'exclude': ['vendor'], 'requireConfig': '/Users/sherov/code/***', 'stylesRoot': '/Users/sherov/code/***'}
JumpToDependency: strings on line ['be/View/Follow']
JumpToDependency: space delimited words on line ['be/View/Follow']
JumpToDependency: Extracted Path {'path': 'be/View/Follow'}
project_settings: starting search for .deprc in:  /Users/sherov/code/***
project_settings: Closest folder with a deprc: /Users/sherov/code/***
project_settings: Using found .deprc within:  /Users/sherov/code/***/.deprc
node_dependents_editor_backend: node_path from settings:  
node_dependents_editor_backend: bin path /Users/sherov/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents-editor-backend/bin/cli.js
node_bridge: Node path: :/usr/local/bin
node_bridge: Executing:  node /Users/sherov/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents-editor-backend/bin/cli.js --filename=/Users/sherov/code/*** --lookup ***
JumpToDependency: After cabinet lookup 
BaseThread: Opening: 
Missing file {'filename': '', '_filename': 'BaseThread.py'}
error: Dependents

Can't find that file
Run_JumpToDependency {'modifier': None, 'etime': '1.8', '_filename': 'BaseThread.py'}
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting the issue! I assume the `***` portions were redactions for privacy (just want to make sure). 

The parsed `requireConfig` value (generated from the `config` value in your `.deprc` file) doesn't seem to have a file extension (not sure if you accidentally redacted that portion). Please double-check that value – since without a requirejs config, the `be/View/Follow` path wouldn't resolve to an actual file.

To help me identify the cause better, you can supply debug info via:

`DEBUG=* node /Users/sherov/Library/Application\ Support/Sublime\ Text\ 3/Packages/Dependents/node_modules/dependents-editor-backend/bin/cli.js --filename=/Users/sherov/code/*** --lookup *** | pbcopy`

* Put the redactions back when executing the command
* Paste the output into a file and remove any private information
* Please paste that edited debug information on this thread

Any additional info is appreciated. Thanks in advance!

**Comment by mikesherov** [comment]
Sent you an email with the information.

**Comment by mikesherov** [comment]
Thanks!x

**Comment by mikesherov** [comment]
looks like resolved location is something `/assets/js/assets/js`, if I removed the `baseUrl` from the require config, it suddenly works.

**Comment by mrjoelkemp** [comment]
Thanks for the details. Will look into it further tonight. The culprit is the fact that your baseUrl has a leading slash. According to the [requirejs spec](http://requirejs.org/docs/api.html#jsfiles), that has special resolution logic. 

Though I think there's room for your baseUrl to become `./` (which is what it defaults to if you don't supply one) and still work in prod, I'd rather add a special rule in my [amd resolver](https://github.com/mrjoelkemp/node-module-lookup-amd/blob/51e4f4125f87ef6e0dd97a4a543d5950dda16509/index.js#L40-L45) to handle the leading slash case (avoiding the redundant baseUrl of `assets/js/assets/js`).

I'll try to get in a fix tonight and have that released to package control so that you can update Dependents tomorrow morning.

Thanks again.

**Comment by mrjoelkemp** [comment]
That was precisely it. I pushed the fix all the way through and submitted it for a package control release (should be available as a Dependents package update in an hour). Please let me know if the fix doesn't resolve your issue. 

I imagine this bug would have also broken the Find Dependents feature. Thanks a ton for reporting it. 

Please feel free to report any additional bugs or pain points.

**Comment by mrjoelkemp** [comment]
FYI, this bug fix has been propagated to Find Dependents. The other features (view tree and find entry points) will get this fix shortly. Thanks again for reporting!
